import type { Metadata } from 'next'
import { type PropsWithChildren } from 'react';
import { Inter } from 'next/font/google';

import './globals.css';

// Sans font
const sans = Inter({ subsets: ['latin'], variable: '--font-sans' });

// TODO: update "name" and dependencies in package.json
// TODO: update favicon
// TODO: update metadata
export const metadata: Metadata = {
  title: 'Next Template',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={`${sans.variable} font-sans`}>{children}</body>
    </html>
  );
}
